### ISSUE TITLE
Cannot add a new species or genus

### ISSUE THREAD

**Issue by blakewillson** [nbw/treelib_elixir#27]
When trying to add a new species or genus, "Response is not ok". They cannot be created.
This is becoming a problem as I now have 20 species that I cannot display.

**Comment by nbw** [comment]
Bug with creating a species/genus/family with a blank description. Fixed in commit [774590f52579a820bc047fa784906058f66f950d](https://github.com/nbw/treelib_elixir/commit/774590f52579a820bc047fa784906058f66f950d)
